
name: build&test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test-unittests:
   runs-on: ${{ matrix.os }}
   strategy:
    matrix:
      os: [windows-latest, ubuntu-latest, macos-latest]
   steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: tests/AsyncNavigation.Tests

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: tests/AsyncNavigation.Tests

    - name: Run tests
      run: dotnet test --configuration Release --no-build  --logger "console;verbosity=detailed"
      working-directory: tests/AsyncNavigation.Tests

  build-avaloniaui-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: samples/Sample.Avalonia.Desktop
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: samples/Sample.Avalonia.Desktop
      
  build-avaloniaui-browser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: samples/Sample.Avalonia.Browser
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: samples/Sample.Avalonia.Browser
      
  build-wpf:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: samples/Sample.Wpf
    - name: Build WPF Sample
      run: dotnet build --configuration Release --no-restore
      working-directory: samples/Sample.Wpf
